SYL-186 create new gateway payplug Apple pay
synolia/SyliusPayPlugPlugin pull request #103
Opened 2022-10-10 12:29 UTC by tuyetrinhvo

2022-10-11 07:54 UTC, TheGrimmChester requested changes

2022-10-11 07:54 UTC, TheGrimmChester commented on src/Gateway/Form/Type/ApplePayGatewayConfigurationType.php
> +                    $baseCurrencyCode = $baseCurrency->getCode();
not needed

2022-10-11 07:54 UTC, TheGrimmChester commented on src/Gateway/Form/Type/ApplePayGatewayConfigurationType.php
> +                    if ($baseCurrencyCode !== ApplePayGatewayFactory::BASE_CURRENCY_CODE) {
not needed

2022-10-12 14:46 UTC, flochntrl approved these changes

2022-10-12 15:16 UTC, merged