update README.md
synolia/SyliusPayPlugPlugin pull request #57
Opened 2021-09-07 13:55 UTC by tuyetrinhvo

2021-09-13 11:05 UTC, TheGrimmChester commented on README.md
> +9. Process translations
You can also add the PaymentMethodTrait \Entity\Traits\PaymentMethodTrait

2021-09-13 11:06 UTC, TheGrimmChester requested changes

2021-09-13 11:06 UTC, TheGrimmChester commented on README.md
> +9. Process translations
You can also add the PaymentMethodTrait \Entity\Traits\PaymentMethodTrait

2021-09-24 09:33 UTC, TheGrimmChester commented on README.md
> +9. Process translations
I will do it!

2021-09-24 09:48 UTC, TheGrimmChester approved these changes

2021-09-28 09:45 UTC, oallain approved these changes

2021-09-28 09:45 UTC, merged